notifications:
  email: false
git:
  quiet: true
  depth: 1

language: java
python: 3

service:
- docker

addons:
  apt:
    update: true
    packages:
    - sudo
    - lsof
    - wget
    - bash
    - curl
    - jq
    - docker-ce
    - python3-dev
    - python3-pip
    - python3-six
    - python3-setuptools

install: true
before_install:
- docker-compose -v
- export PATH=$HOME/.local/bin:$PATH
- pip3 install --user $(whoami) --upgrade pip >/dev/null # pip3 -> pip
- pip install --user $(whoami) --upgrade docker-compose httpie >/dev/null 2>&1
- http --version --debug
- docker-compose -v
#
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 80 8001 8002 8080 5432

jobs:
  include:

  - stage: test
    name: helidon-mp-jpa
    jdk: openjdk8
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw >/dev/null
    - java -jar $TRAVIS_BUILD_DIR/target/*-all.jar  &
    - wait_for 8080
    - http :8080
    - http :8080/not-found ololo=trololo
    - http :8080 hello=world
    - http :8080/openapi
    - http :8080/openapi Accept:application/json
    - http :8080/health
    - http :8080/metrics
    - http :8080/metrics Accept:application/json
    - http :8080/static/helidon-mp-jpa-integration-tests.http
    - http :8080/bank-account username=username balance=123.45
    - http :8080/bank-account
    - stop_any 80 8080

  - stage: test
    jdk: openjdk8
    name: check updates
    script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -U

  - stage: test
    name: helidon-mp-jpa jdk11
    jdk: openjdk11
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw >/dev/null
    - java -jar $TRAVIS_BUILD_DIR/target/*-all.jar  &
    - wait_for 8080
    - http :8080
    - http :8080/not-found ololo=trololo
    - http :8080 hello=world
    - http :8080/openapi
    - http :8080/openapi Accept:application/json
    - http :8080/health
    - http :8080/metrics
    - http :8080/metrics Accept:application/json
    - http :8080/static/helidon-mp-jpa-integration-tests.http
    - http :8080/bank-account username=username balance=123.45
    - http :8080/bank-account
    - stop_any 80 8080

  - stage: test
    jdk: openjdk11
    name: check updates jdk11
    script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -U

cache:
  directories:
  - ~/.m2
  packages: true
  pip: true
